name = "NotyCity"
author = "Fyre520"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3547c25ec1145372b7c4159066d25fcdde7a14cc2bd108cb27683654f60c6004"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
