name = "NotyCity"
author = "Fyre520"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e24decd4f4f33c0e9a6c4677083942cc2ab42ae76332e62d8e707e7178bad5c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
