name = "NotyCity"
author = "Fyre520"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ceab56adba296483e7e03290a56cb0d817ed42ffb69109fa152982598d94703"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
